import type { MusicCategorySlug, VideoCategorySlug } from "./entertainment-navigation";

export type MediaEntry<Category extends string> = {
  slug: string; title: string; bucket: string; franchise: string; premise: string;
  status: "Released" | "Scheduled" | "Coming soon" | "In development";
  releaseType: string; access: string; relatedMedia: string; categories: readonly Category[];
  metadata: readonly string[]; href?: string; featured?: boolean;
};

export const MUSIC_ENTRIES: readonly MediaEntry<MusicCategorySlug>[] = [
  { slug:"kyrie-for-a-dying-star",title:"Kyrie for a Dying Star",bucket:"Singularis",franchise:"Singularis",premise:"A central musical release from the Singularis score, connecting character, location, event, and thematic material.",status:"In development",releaseType:"Score single",access:"Public sample; subscriber release planned",relatedMedia:"Singularis universe and playable prototype",categories:["all","singularis","scores"],metadata:["Score","Instrumental","Science fiction"],featured:true },
  { slug:"signal-and-systems",title:"Signal & Systems: Deep Space Transmission",bucket:"Cryptic Signal",franchise:"Cryptic Signal",premise:"A public sonic-media transmission introducing the label's experimental release language.",status:"Released",releaseType:"Experimental single",access:"Public",relatedMedia:"Cryptic Signal communications",categories:["all","cryptic-signal","songs"],metadata:["Electronic","Experimental"],href:"/releases/singularis-themes-vol-1",featured:true },
  { slug:"next-audio-project",title:"Next Cryptic Design Audio Project",bucket:"Coming Soon",franchise:"Project to be announced",premise:"Construction space for the next approved score, song, soundscape, or collection.",status:"In development",releaseType:"Audio project",access:"Access level under review",relatedMedia:"Related media will be added when approved",categories:["all"],metadata:["In development"],featured:true },
  { slug:"singularis-score-archive",title:"Singularis Score Archive",bucket:"Collections",franchise:"Singularis",premise:"Future score, soundtrack, character, location, event, and thematic music collected by release.",status:"In development",releaseType:"Franchise collection",access:"Subscriber access planned; public samples where approved",relatedMedia:"Games, video, and world communications",categories:["all","singularis","scores","collections"],metadata:["Score","Collection"] },
  { slug:"soundscape-program",title:"World Soundscapes",bucket:"Soundscapes",franchise:"Cryptic Design",premise:"Ambient releases, environmental audio, focus experiences, and authored world-building sound environments.",status:"In development",releaseType:"Soundscape series",access:"Public and subscriber releases",relatedMedia:"Franchise locations and research",categories:["all","soundscapes","collections"],metadata:["Ambient","Environmental"] },
  { slug:"listening-rooms",title:"Listening Rooms",bucket:"Listening Rooms",franchise:"Cryptic Design",premise:"Expanded listening pages with artwork, track context, lyrics when applicable, credits, and connected media.",status:"In development",releaseType:"Listening experience",access:"Access follows each release",relatedMedia:"Music, video, games, and communications",categories:["all","collections"],metadata:["Listening experience"],href:"/entertainment/listening-rooms" },
];

export const VIDEO_ENTRIES: readonly MediaEntry<VideoCategorySlug>[] = [
  { slug:"singularis-overture",title:"Singularis: Overture",bucket:"Singularis",franchise:"Singularis",premise:"A featured visual introduction to the Singularis universe and its evolving narrative systems.",status:"Coming soon",releaseType:"Orientation film",access:"Public sample planned",relatedMedia:"Singularis Arcade, score, and transmissions",categories:["all","singularis","trailers"],metadata:["Orientation","Science fiction"],href:"/releases/singularis-overture",featured:true },
  { slug:"cryptic-design-production",title:"Inside Cryptic Design",bucket:"Behind the Work",franchise:"Cryptic Design",premise:"A production feature connecting design, development, music, and research to the studio capability narrative.",status:"In development",releaseType:"Production feature",access:"Public",relatedMedia:"Professional work and studio research",categories:["all","behind-the-work"],metadata:["Documentary","Process"],featured:true },
  { slug:"next-video-release",title:"Next Cryptic Design Video Release",bucket:"Coming Soon",franchise:"Project to be announced",premise:"Construction space for the next approved episode, short, transmission, trailer, or visualizer.",status:"In development",releaseType:"Video production",access:"Access level under review",relatedMedia:"Related media will be added when approved",categories:["all"],metadata:["In development"],featured:true },
  { slug:"singularis-transmissions",title:"Singularis Transmissions",bucket:"Transmissions",franchise:"Singularis",premise:"Recruitment material, institutional broadcasts, character messages, and classified or redacted footage.",status:"In development",releaseType:"In-universe series",access:"Public samples; subscriber episodes planned",relatedMedia:"Episodes, Operations, and score releases",categories:["all","singularis","transmissions"],metadata:["Broadcast","Narrative"] },
  { slug:"singularis-episodes",title:"Singularis Episodes",bucket:"Series and Episodes",franchise:"Singularis",premise:"Narrative episodes grouped into future seasons and chapters with persistent continue-watching state.",status:"In development",releaseType:"Episodic series",access:"Subscriber access planned",relatedMedia:"Shorts, briefings, and Arcade missions",categories:["all","singularis","episodes"],metadata:["Episodes","Narrative"] },
  { slug:"short-films",title:"Short Films",bucket:"Short Films",franchise:"Standalone",premise:"Standalone narrative productions, experimental cinematic pieces, and franchise-related shorts.",status:"In development",releaseType:"Short-film collection",access:"Assigned per release",relatedMedia:"Franchise and standalone collections",categories:["all","shorts"],metadata:["Short film","Experimental"] },
  { slug:"visualizers-performances",title:"Visualizers & Performances",bucket:"Visualizers",franchise:"Cryptic Signal",premise:"Music visualizers, lyric videos, performances, and audio-linked visual experiences.",status:"In development",releaseType:"Music video collection",access:"Public where approved",relatedMedia:"Songs, scores, and listening rooms",categories:["all","visualizers"],metadata:["Visualizer","Performance"] },
];

export function mediaEntriesFor<Category extends string>(entries: readonly MediaEntry<Category>[], category: Category) {
  return entries.filter((entry) => entry.categories.includes(category));
}
