import { randomUUID } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { getCharacterStore } from "@/lib/character-store";
import { membershipSandboxEnabled } from "@/lib/membership-store";
import { getRpgContentStore } from "@/lib/rpg-content-store";
import { requireSandboxMember } from "@/lib/sandbox-session";

async function ownedActiveCharacter(request: NextRequest, id: string) { const accountId = requireSandboxMember(request); if (!accountId) return { error: NextResponse.json({ error: "Authentication required" }, { status: 401 }) }; const character = await getCharacterStore().findByOwner(accountId); if (!character || character.id !== id) return { error: NextResponse.json({ error: "Character not found" }, { status: 404 }) }; return { character }; }
export async function GET(request: NextRequest, context: { params: Promise<{ id: string }> }) { if (!membershipSandboxEnabled()) return NextResponse.json({ error: "RPG sandbox is disabled" }, { status: 503 }); const { id } = await context.params; const ownership = await ownedActiveCharacter(request, id); if ("error" in ownership) return ownership.error; return NextResponse.json({ content: await getRpgContentStore().snapshot(id) }); }
export async function POST(request: NextRequest, context: { params: Promise<{ id: string }> }) { if (!membershipSandboxEnabled()) return NextResponse.json({ error: "RPG sandbox is disabled" }, { status: 503 }); const { id } = await context.params; const ownership = await ownedActiveCharacter(request, id); if ("error" in ownership) return ownership.error; if (ownership.character.status !== "active") return NextResponse.json({ error: "Only active characters can advance quests" }, { status: 409 }); try { const body = await request.json(); const requestId = request.headers.get("idempotency-key") ?? randomUUID(); const now = new Date().toISOString(); if (body.action === "start") await getRpgContentStore().start({ characterId: id, questId: body.questId, requestId, occurredAt: now }); else if (body.action === "evidence") await getRpgContentStore().evidence({ characterId: id, questId: body.questId, objectiveId: body.objectiveId, evidenceEventId: body.evidenceEventId ?? randomUUID(), requestId, occurredAt: now }); else return NextResponse.json({ error: "Unknown quest action" }, { status: 422 }); return NextResponse.json({ content: await getRpgContentStore().snapshot(id) }, { status: 201 }); } catch (error) { return NextResponse.json({ error: (error as Error).message }, { status: /Idempotency/.test((error as Error).message) ? 409 : 422 }); } }

