"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import AvatarStudio from "@/components/AvatarStudio";
import { AVATAR_OUTFITS, AVATAR_SKIN_TONES, AVATAR_TRAITS, DEFAULT_AVATAR_RECIPE, type AvatarRecipe } from "@/lib/avatar";
import { CHARACTER_ARCHETYPES, type PublicCharacterIdentity } from "@/lib/characters";
const steps = ["Identity", "Form", "Style", "Signal", "Review"];
export default function CharacterCreator() {
  const [step, setStep] = useState(0), [name, setName] = useState(""), [handle, setHandle] = useState(""), [archetype, setArchetype] = useState<string>(CHARACTER_ARCHETYPES[0]), [bio, setBio] = useState("");
  const [avatar, setAvatar] = useState<AvatarRecipe>(DEFAULT_AVATAR_RECIPE), [created, setCreated] = useState<PublicCharacterIdentity | null>(null), [error, setError] = useState<string | null>(null), [saving, setSaving] = useState(false), [authenticated, setAuthenticated] = useState(false), [serviceMode, setServiceMode] = useState<"supabase" | "sandbox" | "disabled">("disabled"), [sessionLoaded, setSessionLoaded] = useState(false);
  useEffect(() => { fetch("/api/membership/session").then((r) => r.json()).then((p) => { setAuthenticated(Boolean(p.authenticated)); setServiceMode(p.mode ?? "disabled"); }).catch(() => setAuthenticated(false)).finally(() => setSessionLoaded(true)); }, []);
  const patchAvatar = (patch: Partial<AvatarRecipe>) => setAvatar((current) => ({ ...current, ...patch }));
  async function startPreviewSession() { setError(null); const response = await fetch("/api/membership/session", { method: "POST" }); const payload = await response.json(); if (!response.ok) return setError(payload.error ?? "Local preview session could not be started"); setAuthenticated(Boolean(payload.authenticated)); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); try { const response = await fetch("/api/characters", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ name, handle, archetype, bio, avatarRecipe: avatar }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Character could not be created"); setCreated(payload.character); } catch (caught) { setError((caught as Error).message); } finally { setSaving(false); } }
  if (created) return <section className="forge-complete panel"><AvatarStudio recipe={created.avatarRecipe} label={created.name} compact /><div><span className="kicker">Signal established</span><h2 className="section-title">{created.name}</h2><p className="muted">Your persistent Cryptic persona is ready.</p><Link href="/account/character" className="button">Enter Character Home</Link></div></section>;
  if (!sessionLoaded) return <p className="ui-loading" aria-busy="true">Checking local preview session…</p>;
  if (!authenticated && serviceMode === "sandbox") return <section className="panel flex max-w-xl flex-col items-start gap-4 p-5"><h2 className="font-medium">Enter the Character Forge</h2><p className="muted">Start a local preview session. It creates no real account and sends no personal or biometric data.</p>{error ? <p role="alert" className="text-red-300">{error}</p> : null}<button type="button" className="button" onClick={startPreviewSession}>Start local preview</button></section>;
  if (!authenticated) return <section className="panel flex max-w-xl flex-col items-start gap-4 p-5"><h2 className="font-medium">Sign in to enter the Character Forge</h2><p className="muted">A verified free member account is required before creating your persistent character.</p><div className="flex flex-wrap gap-3"><Link href="/account/create" className="button">Create free account</Link><Link href="/account/sign-in" className="button secondary">Sign in</Link></div></section>;
  return <form onSubmit={submit} className="character-forge"><section className="character-forge__stage"><AvatarStudio recipe={avatar} label={name || "Unnamed persona"} /><div className="forge-identity"><span className="kicker">Live persona</span><strong>{name || "Awaiting identity"}</strong><span>{archetype}</span></div></section><section className="character-forge__controls panel"><nav className="forge-steps" aria-label="Character Forge steps">{steps.map((label, index) => <button type="button" key={label} aria-current={step === index ? "step" : undefined} onClick={() => setStep(index)}><span>{index + 1}</span>{label}</button>)}</nav><div className="forge-control-body"><span className="kicker">Step {step + 1} of {steps.length}</span><h2 className="section-title">{steps[step]}</h2>
    {step === 0 ? <div className="forge-fields"><label>Display name<input required maxLength={32} value={name} onChange={(e) => setName(e.target.value)} /></label><label>Handle<input required minLength={3} maxLength={32} pattern="[a-z0-9][a-z0-9-]{1,30}[a-z0-9]" value={handle} onChange={(e) => setHandle(e.target.value.toLowerCase())} /></label></div> : null}
    {step === 1 ? <div><fieldset><legend>Skin material</legend><div className="choice-grid">{AVATAR_SKIN_TONES.map((value) => <button type="button" key={value} aria-pressed={avatar.skinTone === value} onClick={() => patchAvatar({ skinTone: value })}>{value}</button>)}</div></fieldset><fieldset><legend>Optional traits</legend><div className="choice-grid">{AVATAR_TRAITS.map((value) => <button type="button" key={value} aria-pressed={avatar.trait === value} onClick={() => patchAvatar({ trait: value })}>{value}</button>)}</div></fieldset></div> : null}
    {step === 2 ? <div><fieldset><legend>Outfit</legend><div className="choice-grid">{AVATAR_OUTFITS.map((value) => <button type="button" key={value} aria-pressed={avatar.outfit === value} onClick={() => patchAvatar({ outfit: value })}>{value}</button>)}</div></fieldset><fieldset><legend>Signal color</legend><div className="choice-grid">{(["cyan", "gold", "magenta", "green"] as const).map((value) => <button type="button" key={value} aria-pressed={avatar.accent === value} onClick={() => patchAvatar({ accent: value })}>{value}</button>)}</div></fieldset></div> : null}
    {step === 3 ? <fieldset><legend>Choose an origin signal</legend><div className="choice-grid">{CHARACTER_ARCHETYPES.map((value) => <button type="button" key={value} aria-pressed={archetype === value} onClick={() => setArchetype(value)}>{value}</button>)}</div></fieldset> : null}
    {step === 4 ? <div className="forge-fields"><label>Biography <span>Optional · private by default</span><textarea maxLength={280} value={bio} onChange={(e) => setBio(e.target.value)} /></label><p className="forge-boundary">Appearance shapes presentation only. It cannot grant permissions, purchases, membership, or progression.</p></div> : null}
    {error ? <p role="alert" className="text-red-300">{error}</p> : null}<div className="forge-actions"><button type="button" className="button secondary" disabled={step === 0} onClick={() => setStep((value) => Math.max(0, value - 1))}>Back</button>{step < 4 ? <button type="button" className="button" onClick={() => setStep((value) => Math.min(4, value + 1))}>Continue</button> : <button type="submit" className="button" disabled={saving || !name || !handle}>{saving ? "Establishing…" : "Establish persona"}</button>}</div></div></section></form>;
}
