import Link from "next/link";
import type { MediaEntry } from "@/lib/media-catalog";

function MediaCard({ entry }: { entry: MediaEntry<string> }) {
  const content = <><div className="arcade-card__heading"><span>{entry.franchise}</span><strong>{entry.status}</strong></div><h3>{entry.title}</h3><p>{entry.premise}</p><dl><div><dt>Bucket</dt><dd>{entry.bucket}</dd></div><div><dt>Type</dt><dd>{entry.releaseType}</dd></div><div><dt>Access</dt><dd>{entry.access}</dd></div><div><dt>Related</dt><dd>{entry.relatedMedia}</dd></div><div><dt>Metadata</dt><dd>{entry.metadata.join(" · ")}</dd></div></dl><span className="arcade-card__action">{entry.href ? "Open release →" : "Follow / notify — coming later"}</span></>;
  return entry.href ? <Link className="arcade-card" href={entry.href}>{content}</Link> : <article className="arcade-card arcade-card--construction">{content}</article>;
}

function MediaSection({ eyebrow, title, entries }: { eyebrow: string; title: string; entries: readonly MediaEntry<string>[] }) { return <section className="arcade-section"><div className="section-heading"><div><span className="kicker">{eyebrow}</span><h2 className="section-title">{title}</h2></div></div><div className="arcade-grid">{entries.map((entry) => <MediaCard entry={entry} key={entry.slug} />)}</div></section>; }

export default function MediaMvpPage({ kind, selectedLabel, rootView, entries, filtered }: { kind: "Music" | "Video"; selectedLabel: string; rootView: boolean; entries: readonly MediaEntry<string>[]; filtered: readonly MediaEntry<string>[] }) {
  const music = kind === "Music";
  return <main className={`arcade-page media-mvp media-mvp--${kind.toLowerCase()}`}><header className="destination-hero"><div className="shell destination-hero__content"><span className="eyebrow">{kind} / MVP</span><h1 className="display-title">{rootView ? (music ? "Hear the worlds of Cryptic Design." : "Watch the worlds of Cryptic Design.") : selectedLabel}</h1><p>{rootView ? (music ? "Songs, scores, soundscapes, collections, and connected listening experiences." : "Narrative video, transmissions, production stories, and audio-linked visual experiences.") : `Explore ${selectedLabel} across Cryptic Design ${kind}.`}</p><div className="hero-actions"><a className="button" href={`#${kind.toLowerCase()}-catalog`}>Explore {kind}</a><Link className="button secondary" href="/entertainment">Entertainment home</Link></div></div></header><div className="shell page-stack" id={`${kind.toLowerCase()}-catalog`}>{rootView ? <><MediaSection eyebrow="Featured" title={`Featured in ${kind}`} entries={entries.filter((entry) => entry.featured)} /><MediaSection eyebrow={`All ${kind}`} title={`The complete ${kind.toLowerCase()} catalog`} entries={entries} /><MediaSection eyebrow="In development" title={`Known future ${kind.toLowerCase()} work`} entries={entries.filter((entry) => entry.status !== "Released")} /></> : <MediaSection eyebrow={selectedLabel} title={`${selectedLabel} in ${kind}`} entries={filtered} />}</div></main>;
}
